#[derive(Debug, Clone)]
pub enum Token {
    LeftParen { line: u64 },
    RightParen { line: u64 },
    LeftBrace { line: u64 },
    RightBrace { line: u64 },
    Comma { line: u64 },
    Dot { line: u64 },
    Minus { line: u64 },
    Plus { line: u64 },
    Semicolon { line: u64 },
    Slash { line: u64 },
    Star { line: u64 },
    Bang { line: u64 },
    BangEqual { line: u64 },
    Equal { line: u64 },
    EqualEqual { line: u64 },
    Greater { line: u64 },
    GreaterEqual { line: u64 },
    Less { line: u64 },
    LessEqual { line: u64 },
    Identifier { line: u64, lexeme: String },
    String { line: u64, value: String },
    Number { line: u64, value: f32 },
    And,
    Class,
    Else,
    False,
    Fun,
    For,
    If,
    Nil,
    Or,
    Print,
    Return,
    Super,
    This,
    True,
    Var,
    While,
    Eof,
}
